# Generated by Django 5.1 on 2024-08-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_phone_number_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
